services:
  gameserver:
    image: ${DOCKER_REGISTRY-}gameserver
    build:
      context: .
      dockerfile: GameServer/Dockerfile
    depends_on:
      - mongodb

  mongodb:
    image: mongodb/mongodb-community-server:latest
    ports:
      - '27017:27017'
    restart: always
    environment:
        # MONGO_INITDB_ROOT_USERNAME: <admin-user>
        # MONGO_INITDB_ROOT_PASSWORD: <admin-password>
        MONGO_INITDB_DATABASE: BTRemake-Game
        # MONGO_INITDB_ROOT_USERNAME: root
        # MONGO_INITDB_ROOT_PASSWORD: rootpasswd
    volumes:
      - ./MongoDB/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    # volumes:
    #   - type: bind
    #     source: ./data
    #     target: /data/db