services:

  loki:
    image: grafana/loki:2.9.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    # volumes:
    #   - loki-data:/loki
    networks:
      - app-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    # volumes:
    #   - grafana-data:/var/lib/grafana
    depends_on:
      - loki
    networks:
      - app-network
      
  mongodb:
    image: mongodb/mongodb-community-server:latest
    ports:
      - '27017:27017'
    restart: always
    environment:
        MONGO_INITDB_DATABASE: BTRemake-Game
        # MONGO_INITDB_ROOT_USERNAME: root
        # MONGO_INITDB_ROOT_PASSWORD: rootpasswd
    volumes:
      - ./MongoDB/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - app-network
    # volumes:
    #   - type: bind
    #     source: ./data
    #     target: /data/db

  gameserver:
    image: ${DOCKER_REGISTRY-}gameserver
    ports:
      - "8080:80"
    build:
      context: .
      dockerfile: GameServer/Dockerfile
    # volumes:
    #   - ./app/Ressources:/app/Ressources 
    networks:
      - app-network
    depends_on:
      - mongodb
      - grafana
    
  testConsole:
    image: ${DOCKER_REGISTRY-}testconsole
    build:
      context: .
      dockerfile: TestClient/Dockerfile
    environment:
      - API_URL=http://gameserver:8080
    networks:
      - app-network
    depends_on:
      - gameserver

networks:
  app-network:
    driver: bridge