services:
  gameserver:
    image: ${DOCKER_REGISTRY-}gameserver
    build:
      context: .
      dockerfile: GameServer/Dockerfile
    depends_on:
      - mongodb

  mongodb:
    image: mongodb/mongodb-community-server:latest
    ports:
      - '27017:27017'
    # volumes:
    #   - type: bind
    #     source: ./data
    #     target: /data/db