services:

  aspire:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:9.0
    ports:
      - '18888:18888'
      - '4317:18889'
      - '4318:18890'
    environment:
        ASPIRE_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: true
        DASHBOARD__OTLP__AUTHMODE: ApiKey
        DASHBOARD__OTLP__PRIMARYAPIKEY: ApiKeyAspire
       # OTEL_EXPORTER_OTLP_PROTOCOL : grpc
        OTEL_EXPORTER_OTLP_ENDPOINT : http://gameserver:4317
        ASPIRE_DASHBOARD_OTLP_HTTP_ENDPOINT_URL : http://gameserver:4318
       #  OTEL_SERVICE_NAME : NO_OTEL_NAME
    networks:
      - app-network

  mongodb:
    image: mongodb/mongodb-community-server:latest
    ports:
      - '27017:27017'
    restart: always
    environment:
        MONGO_INITDB_DATABASE: BTRemake-Game
        # MONGO_INITDB_ROOT_USERNAME: root
        # MONGO_INITDB_ROOT_PASSWORD: rootpasswd
    volumes:
      - ./MongoDB/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - app-network
    # volumes:
    #   - type: bind
    #     source: ./data
    #     target: /data/db

  gameserver:
    image: ${DOCKER_REGISTRY-}gameserver
    ports:
      - "8080:80"
    build:
      context: .
      dockerfile: GameServer/Dockerfile
    # volumes:
    #   - ./app/Ressources:/app/Ressources 
    networks:
      - app-network
    depends_on:
      - mongodb
      - aspire
    
  testConsole:
    image: ${DOCKER_REGISTRY-}testconsole
    build:
      context: .
      dockerfile: TestClient/Dockerfile
    environment:
      - API_URL=http://gameserver:8080
    networks:
      - app-network
    depends_on:
      - gameserver

networks:
  app-network:
    driver: bridge